function bound = L2(V2, t, param)
    bound = exp(param.alpha1*sqrt(V2)/2/param.beta) ...
        *(param.alpha2*sqrt(V2)/2) ...
        *(exp(-param.beta*t)-exp(-param.alpha0/2*t))/(param.alpha0/2 - param.beta);
end